Repository fga-eps-mds/2021.1-Oraculo-Registros, pull requests merged in 2021-09, with the labels that each got.

#2 #53 Configurar cobertura de testes nos microsserviços
  .gitignore
  package.json
  sonar-project.properties
Labels: DEVOPS, EPS

#1 #60 Configurar envio automático do arquivo do sonarcloud
  .github/workflows/release.yml
Labels: DEVOPS, EPS, DOCS

#3 fga-eps-mds/2021.1-Oraculo#34 Criar um processo
  .dockerignore
  .env
  .sequelizerc
  Dockerfile
  app/index.js
  docker-compose.yml
  index.js
  package-lock.json
  package.json
  sonar-project.properties
  src/Controller/ProcessController.js
  src/Database/config/config.json
  src/Database/config/database.js
  src/Database/index.js
  src/Database/migrations/20210916172019-create-process.js
  src/Model/Process.js
  src/Utils/jwt.js
  src/index.js
  src/routes.js
  tests/database.test.js
  tests/index.test.js
Labels: FEATURE, MDS

#5 Fixes sonarcloud tests
  package.json
Labels: MDS, HOTFIX
