Repository fga-eps-mds/2021.1-Oraculo-Registros, pull requests merged in 2021-11, with the labels that each got.

#20 143 improve record creation
  src/Controller/RecordController.js
  src/Controller/SectionController.js
  src/Controller/UserController.js
  src/Database/migrations/20211018012203-create-user.js
  src/Database/seeders/20211011022156-populate-users.js
  src/Database/seeders/20211017219612-populate-sections.js
  src/Model/User.js
  src/routes.js
  tests/index.test.js
Labels: FEATURE, MDS, MEDIUM

#21 161 edit record
  README.md
  src/Controller/RecordController.js
  src/routes.js
  tests/index.test.js
Labels: FEATURE, MDS, MEDIUM

#22 164 updates history format
  README.md
  src/Controller/RecordController.js
  src/Controller/RecordNumberController.js
  src/Controller/SectionController.js
  src/Controller/UserController.js
  src/Database/index.js
  src/Database/migrations/20210916172019-create-records.js
  src/Database/migrations/20210919185924-create-situations.js
  src/Database/migrations/20211019041645-create-history.js
  src/Model/History.js
  src/Model/Record.js
  src/Model/Situation.js
  src/routes.js
  tests/index.test.js
Labels: FEATURE, MDS, HARD

#23 170 improve record history
  README.md
  package.json
  src/Constants/errors.js
  src/Controller/RecordController.js
  src/Controller/TagController.js
  src/Database/migrations/20211019041645-create-history.js
  src/Model/History.js
  src/routes.js
  tests/index.test.js
Labels: FEATURE, MDS, MEDIUM

#24 Issues/194 increases record per page
  src/Controller/RecordController.js
Labels: FEATURE, MDS, EASY

#25 185 search sei number
  README.md
  src/Controller/RecordController.js
  src/routes.js
  tests/index.test.js
Labels: FEATURE, MDS, MEDIUM

#29 201 fix error endpoint get user by email
  README.md
  src/Controller/UserController.js
  src/routes.js
  tests/index.test.js
Labels: HOTFIX

#30 Endpoint para cadastrar departamento
  README.md
  src/Controller/DepartmentController.js
  src/routes.js
  tests/index.test.js
Labels: FEATURE, MDS, EASY
